export const GET_REQUEST_MOVIE = "GET_REQUEST_MOVIE";
export const GET_SUCCESS_MOVIE = "GET_SUCCESS_MOVIE";
export const GET_FAILURE_MOVIE = "GET_FAILURE_MOVIE";
export const GET_PRODUCT_ID_SUCCESS_MOVIE = "GET_PRODUCT_ID_SUCCESS_MOVIE";
